### ISSUE TITLE
Support explicit path to thrift executable

### ISSUE THREAD

**Issue by smeder** [thomaslee/gradle-thrift-plugin#1]
Would it be possible to add support for explicitly specifying the location of the thrift executable? Seems like the code is almost there for that...

**Comment by thomaslee** [comment]
Ugh, silly oversight. All the code is in place to do it, but there's no mutator in v0.0.5. Fixed in 0a668119 & I'll cut v0.0.6 shortly. Should be up on Maven Central over the next day or so. Thanks for the nudge!
